<a href="https://colab.research.google.com/github/Nilswonderland/my_workings/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [6]:
import numpy as np
from scipy import stats
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [29]:
numbers = np.random.normal(100.0, 15, 1000)
numbers

array([ 95.16966966,  91.33779693, 108.77354699, 132.30706716,
       110.49384186,  59.22231897,  84.14500328, 111.97835707,
        88.37792591,  94.63177122, 123.3250604 , 110.05310778,
       108.89287024, 104.02470118, 111.90073865, 115.53222596,
        91.55405808, 126.68727925, 106.41313278, 100.63158257,
        90.70047442,  83.30946815,  98.78120134,  99.42652198,
       107.45591718, 101.00372335,  86.25971871,  95.42058135,
        92.94350591,  68.677766  ,  90.62005468, 119.4971724 ,
       106.71786768, 109.43607835, 122.13476579, 112.42146165,
        81.7968804 , 119.37249256,  98.43691133, 108.18149672,
        67.49364545,  86.77495305, 115.57324306, 103.97116352,
        95.88262795,  94.54901718, 100.44857075,  99.95744696,
       111.49184997, 111.58180829,  88.26618437,  96.66564624,
       117.9245352 ,  99.01638663,  71.57300155, 106.62273175,
        94.66144834, 111.1295709 ,  69.91470318,  86.32614814,
       113.17629132, 105.22808706,  75.90762778, 101.57522338,
       103.02327064, 122.18251121, 101.66359203, 115.24590772,
        96.91462673,  98.31966417, 105.7914941 , 121.71717836,
        98.14099059,  86.75044019,  85.32491896,  80.75159101,
       115.18803012,  84.85530391,  93.25659666, 124.9541508 ,
       112.68415975,  75.63469688,  98.87820169, 102.20755775,
       105.56749766, 140.22336312, 107.83722275,  88.81046365,
        57.23248073,  92.25444061, 111.68089847,  95.58698821,
        96.86035361,  85.80358893, 110.03058677, 107.32564862,
       114.00299879, 117.68509675,  94.75083529, 124.42163044,
       101.89584854,  84.98881055, 110.4314664 , 102.81543002,
       105.76900593,  99.28938794,  82.85456589, 121.56542115,
        93.44394805,  74.58426092,  95.61999631,  93.80840553,
        90.59319991, 109.06922949, 113.82066341, 117.14802222,
       120.29724275, 112.33267929, 107.65245362,  78.24811116,
        94.07176238, 101.4629855 ,  91.77303797,  83.21831382,
       122.5579424 ,  93.31859055, 104.81017268, 102.63827158,
        82.00964238,  97.45544759,  98.01135996,  71.59369328,
        85.57031648,  92.04933637,  84.95548888, 109.81545716,
       108.73641226, 106.97868981,  95.41176937,  93.07356533,
        88.4176228 , 100.94778539,  93.86631688,  91.93230599,
        88.91232499, 102.41460424, 105.14711911, 109.13349526,
       109.98571259, 101.69182191,  98.19151344,  92.79524155,
        86.37602065,  88.56837967, 117.49416636, 116.29552483,
       100.30997465, 116.3434413 , 100.47272116,  93.09637071,
        86.37446493,  85.77892618,  81.32954327, 104.0841276 ,
        84.71158219,  78.04691408, 106.30911178, 113.47608728,
        96.14736789,  86.98102575,  67.60292198,  94.37645968,
        87.32808132, 108.69870815,  99.30346286,  84.61635047,
        93.91052318,  97.51263898,  99.92896679, 119.99029278,
       101.78421171, 114.41642148, 101.4467872 , 108.33261329,
       100.00295809, 116.69150912,  67.91944045,  85.7603908 ,
        84.82298872, 115.08842007, 124.60304469,  96.04136397,
       102.12035525, 109.63249631, 117.26221219,  73.23704365,
       114.54929216,  75.7600425 ,  91.17165135, 118.38101375,
        94.65291436, 101.919325  ,  89.58551323,  97.9999992 ,
        98.99533726,  90.40239491, 102.51021565, 102.02727642,
        94.32195763,  93.47291258, 110.04964824,  79.52052897,
       129.7874237 ,  93.10190098,  97.52822649, 105.6956457 ,
        89.49078475,  69.51621701, 116.29526838, 114.8307718 ,
        90.20960069, 128.30924381,  87.48322142,  94.22168945,
       109.82972485,  97.3168805 , 110.08712441, 115.25555475,
        83.85200429, 101.5033949 , 113.09917961,  88.56110398,
        94.07623372,  83.146711  , 112.59098731, 117.48618879,
       103.90875368,  89.29728214,  44.47347796, 136.4005423 ,
       113.61461054, 133.94355506, 101.88252226,  80.85035427,
       102.26096321, 102.6724318 , 111.14459735, 110.59591598,
        96.99532411,  96.5284815 , 115.49434497,  99.47611776,
       103.4034594 ,  97.29287732, 104.46299029, 101.43904769,
       102.38310355, 115.41631369, 101.14277606, 127.46938743,
       112.19953843, 104.56128054,  90.27567606,  99.92450475,
        98.68566508, 114.9473083 ,  96.87968531,  90.73320312,
       129.89003024,  96.76325253, 105.88035497,  69.06960958,
       101.4875833 , 107.31045325,  96.26650366,  99.76608319,
        77.91596558,  99.64758024,  92.83316928, 112.89720014,
        81.1387438 ,  96.50174774,  89.58661577,  96.16426334,
       103.16221365,  79.7088303 , 107.26098386,  82.29769317,
       107.26630875, 103.18422817, 108.09529541, 110.40088979,
        93.92886002,  84.09910449, 101.02264345, 128.19098854,
        93.58096641, 116.00179993,  93.78164392,  77.65789498,
       121.49327244,  94.54657935, 100.02843865,  71.68810718,
        90.93658655, 121.40308783, 100.2461969 , 136.78338642,
       103.97032332, 117.25889669, 103.61461629,  75.31783128,
        85.98517076, 114.12386216, 101.20388403, 117.02272589,
       117.20840451, 104.42055927,  68.83498576, 100.23861123,
        88.71566865, 107.36282714, 110.80020298,  87.00950044,
        96.80244208,  70.69821751,  90.6078989 , 117.24067192,
        93.01742939,  90.69915842,  99.14213321, 129.6950853 ,
        99.64953709, 119.60824181,  74.45732106, 104.12294314,
        96.38986938, 112.69208891, 115.66634755,  94.18437003,
       101.6438109 , 120.89033861,  85.80236332, 109.6956996 ,
        71.5772763 , 118.86574269,  93.21974089, 145.92735602,
        88.83558939, 110.13317731, 108.87120838,  87.69957371,
        93.78067448,  88.06565262, 106.23475084,  85.0501687 ,
        82.80179676, 107.81277062,  91.8187156 ,  93.34796295,
       115.89287904,  92.49723605,  97.62257562,  94.03119983,
        80.83279689, 111.7433274 ,  91.36565641,  87.97229231,
       117.25326641,  79.57676653,  76.14730083,  99.41858726,
        82.01984148, 100.44865764,  95.62828744, 111.49782965,
        86.43454965, 107.72645837, 113.89020736, 126.77043848,
        76.29942698,  96.80499615, 117.31815256,  81.92870549,
       115.40816326, 117.45492055, 108.26801801,  93.12514507,
       107.91732243,  93.64760941, 107.31443373, 109.85423041,
        90.39693508,  78.92458817, 110.09033989,  80.79574562,
        62.12374484, 113.23347268,  98.75743435,  92.98865471,
        79.11111166,  93.71368745, 112.3386664 , 116.68164558,
        91.56907876, 105.38117365,  98.62893707,  95.52167904,
        87.48372343, 118.19100414,  95.3519404 ,  98.4351439 ,
        86.55235454,  97.41179974,  98.93762731, 120.96255498,
        82.95820401, 107.70473735,  89.38715952, 129.29429348,
        93.07207744,  87.21209112,  98.51789696,  89.05752307,
        89.92049741, 100.4465868 , 108.77952517, 109.25109729,
        82.25492357,  85.00314412, 116.30628649,  93.25838107,
        64.87847448, 129.84432754, 104.74387732,  85.01017842,
       109.29299194, 101.30491629,  82.32330159,  89.08748493,
        96.82673936,  92.98315607,  98.51192842, 103.50640146,
        81.4864364 ,  96.15991707, 118.86801164,  75.75508168,
        79.69765872, 106.62563479,  95.62689441,  85.26110384,
        93.23693256,  90.03800264, 101.4251485 ,  86.51117223,
        73.74393414,  88.53157918, 122.57646984, 111.8828328 ,
        92.16600647, 119.16147104,  98.30779492, 120.10684995,
        94.46706376,  84.27313804, 108.88088091,  81.64440327,
       113.52228225,  88.06400862,  79.667986  , 109.80223057,
        93.67076134,  97.36196628, 106.95036743, 120.80824156,
       105.46488941,  83.02807089,  68.7463127 ,  92.03683716,
       101.05295175,  94.26050178,  77.69256634, 128.75357254,
       115.56280913,  81.18714309,  78.33018095,  91.07315302,
        97.19146811,  93.36424144,  93.60604809, 106.44144976,
        79.96490161, 103.70320324,  88.18827943, 108.98454264,
        57.87266693,  89.48204323, 119.57212518, 103.56770411,
        84.08613885,  79.1697052 , 110.01086182,  92.30135275,
        98.15730541, 123.70578431, 110.57930996,  85.63348228,
       126.23767135, 110.1953382 , 103.22944021,  77.43647657,
       121.92704993, 115.0947891 , 109.75933271,  79.04391918,
        90.59699135, 116.67643349, 103.48779373, 102.37217168,
       125.82370774,  92.73854723,  97.17804783,  70.75912949,
        95.9945549 , 104.70692116, 104.38059054, 109.52768478,
       131.72406044, 125.25259849, 101.58304817, 102.39636919,
        88.94467517,  98.94958949, 104.07926315, 112.24224199,
        95.57382063, 100.15195158,  92.74025064, 106.98961693,
       105.77408046, 118.70979817, 141.28136563,  86.48493544,
       102.58069369, 118.34916803, 110.33496136,  93.87442529,
        94.61280989,  96.66447213,  95.26944485,  88.68908037,
        97.619808  ,  98.49156381,  85.15038134,  87.52656006,
        80.03583441, 115.30793419,  83.08740873,  82.78898389,
       115.0761821 , 130.55584053,  93.54818242, 105.00860168,
        66.66881134,  74.05493535, 122.58204669, 114.07684506,
        88.72420625, 113.55807726, 101.16924257, 103.17521103,
        90.63621423, 108.5835955 , 113.05566259,  94.62065591,
        84.08141291,  95.22114299,  89.50938105, 104.13693493,
       121.44732315,  89.94241271, 104.10803948,  79.1193806 ,
        77.81026196,  97.70037531,  85.63793041, 111.82693277,
        75.74403568, 112.56085666, 120.33700962, 119.02593499,
       112.52822963,  69.84759164,  76.81397257,  83.87335962,
       101.799133  ,  94.58173011,  72.91316151,  74.22449817,
       107.76642981,  89.48544766,  79.09628821, 116.04073891,
        66.96683191, 116.9052638 ,  98.27220307,  94.88945375,
        95.67543601,  74.4902852 , 106.13389049, 117.32844592,
       113.81706182, 102.23409665, 113.18189222, 117.81651597,
        86.89115205,  73.1631058 , 105.72153915, 105.98940784,
       127.60089621, 116.1196206 , 101.78091113,  69.95498289,
       103.21760439,  93.39682084,  98.71476432, 105.62750881,
       109.52197402, 107.58683651, 108.89090828,  93.88567326,
       104.45510663, 113.23116798,  99.03730673, 111.73213102,
       106.58889331,  96.46962786, 121.68874657, 100.16464363,
       112.74913058, 107.13477676, 112.46954403,  93.06973944,
        84.42079911,  90.00565821, 109.94700103, 100.99838524,
        93.37186359, 103.93972124, 110.82481603, 112.20334846,
       103.81209816, 110.62142158,  78.28204585,  73.28976699,
        83.55483906,  94.18922699,  69.74890062, 128.68822484,
        86.39250488, 110.80217259,  88.45778694,  96.93027532,
        96.0973086 , 106.42485175, 110.71788612, 101.03046867,
        63.19151139,  95.12625565, 118.85326493, 105.70839806,
        68.44468734, 100.16484924,  84.96098623,  79.66287076,
       110.79448056, 110.69322171, 109.69331806,  99.88240291,
        84.33431426, 104.72253515,  86.58095564,  81.74216977,
        82.26199891, 100.48020372, 108.47993297, 112.42963335,
        92.66203238, 119.80845135, 113.36648337,  75.68504045,
        97.73139593,  83.33815298,  93.98516279,  96.71755498,
       147.03192904, 102.17066551, 125.09075687, 113.64861335,
        66.26733399,  83.83594979, 106.64568843, 104.62595071,
       138.45166265,  98.46617554,  85.78540878,  94.26793052,
        92.40962824,  95.72810818, 107.08405021,  95.11046352,
       113.1177717 , 102.46492033, 120.87549854,  77.31487947,
        80.45827321,  83.77659351, 100.02151925, 109.73135384,
       122.18439324,  95.35833192, 125.54868888, 123.2191031 ,
        86.37988444,  89.3049902 ,  82.08872763,  95.90402667,
       111.92475046, 117.83606078, 115.13351392,  98.09469802,
       109.79412009,  97.57770744, 106.58223611,  94.42779478,
        74.47717607,  76.51327555,  88.95852606,  98.37653102,
       101.19978847, 107.16605705, 118.41989139, 114.62788105,
        93.58018855,  96.10434577, 114.44970427,  91.02539157,
       105.83892779, 114.24705705, 101.62447936,  94.97875134,
        94.88316042, 105.94595315,  83.26616835, 106.82380513,
       107.36340881, 100.78643865, 112.90941055,  90.79794   ,
        80.52864544,  79.87500167, 124.13735639,  87.32921143,
        91.53117132,  96.21562728, 124.8979016 , 113.42249998,
       107.748138  , 101.50042993,  77.22318282, 106.78058773,
        95.41976137, 108.46665598,  94.54619601, 129.52310473,
       112.7020338 , 106.71210188,  86.55553253, 119.65067121,
        74.74694384,  81.02945217, 119.31143564, 131.19959914,
       105.68752616,  90.24326794, 111.71542299, 106.65602016,
       111.79087231, 108.44345341, 100.04408919,  95.63818292,
        90.01256211, 104.09154135,  82.42951342,  98.08066037,
        85.47171987,  90.21026889,  98.65562598,  95.61457375,
        74.27120621,  74.14503093,  90.31123558,  89.12604289,
        80.19276545, 104.5127869 ,  96.64785201, 114.33727787,
       106.13458366,  94.77401882, 104.82407739, 117.23990472,
       102.11640206,  89.60410068, 119.21169605,  76.23736136,
        91.29321035, 108.0201296 , 102.19878712, 101.54203724,
        82.00715829,  98.62041914, 103.82670588,  87.97935816,
       106.12827847,  68.36677755, 110.1970244 ,  93.87119664,
        96.64316797, 112.94162031, 129.170672  ,  83.45021769,
        82.96156343, 112.99294704,  82.64227167, 105.50305703,
       105.28750783,  79.61707977, 100.65071509, 101.9137835 ,
       109.55593613, 103.83945367,  74.23882321, 106.08408238,
       109.21952388, 126.6975682 ,  86.66247496, 112.86490913,
       121.60508353,  97.55148336,  81.4116661 , 119.91694118,
        92.13133008,  82.28820059,  96.13560175, 118.2847252 ,
       122.72437599, 102.49736973,  74.49606169, 114.34052233,
        76.92203388,  87.72359768, 105.43768937, 110.43373766,
        93.19307399,  75.6994858 ,  82.88968736, 122.23091364,
        61.34984117, 132.46664361, 127.16549455, 107.81583679,
       103.36577795, 112.26247033, 112.41790852,  88.19071136,
        76.52464523, 112.3645227 ,  72.52177338, 101.0973279 ,
       129.01534042, 126.09239887,  87.65161954,  88.58302499,
        95.64946494,  82.45795383,  99.82472204,  87.40819167,
        89.79118874,  87.06985109, 108.28260487, 101.53066057,
       125.90269944,  99.68251485,  95.27687244, 109.32671825,
        87.53462184, 119.09452499, 107.69954963, 107.44698451,
        95.78172118,  89.08648529, 107.82099702,  87.40531913,
        78.77044021, 103.91037416,  77.30438945,  80.52669488,
       102.31863526, 134.3627027 , 100.67043472,  77.80874828,
        97.28829046,  99.3181908 , 117.59595179,  85.12657121,
        92.69532728, 130.56143243,  95.26641862, 122.80541243,
       100.82596955,  96.53338769, 102.98261531,  85.57724551,
       135.56766315,  89.07421167,  94.4318609 , 102.16504385,
       107.20815097,  97.68767598, 115.25448257, 136.30739559,
        87.91762464, 105.72331143, 103.65182376,  92.08335281,
        94.81865165, 103.5625331 ,  95.68798075,  76.0477717 ,
       113.58461004, 107.56688645,  99.05331276, 125.14833078,
       112.47910073,  81.5449548 , 100.93165917,  83.47385539,
        73.97499966, 118.30431028, 102.16882743,  56.23192495,
        96.42728908,  98.5799547 , 118.84969434, 107.35965755,
        97.69873576, 107.24184701, 107.05468507,  63.89292322,
        97.14146037,  77.81856488, 101.07104578,  87.57019094,
       109.7672064 ,  99.48890823,  78.34788068,  78.19512261,
       110.67636808,  98.39697102,  92.27586692, 117.96374484,
       115.75231517, 100.4227955 , 121.25218885,  80.55034466,
       124.12910667, 101.07782374, 104.76565948,  91.6569134 ,
        88.94404847,  84.22436318,  81.08602589,  99.27323436,
       107.53277999, 105.25735824,  96.33016729,  69.81419384,
       112.36330272, 125.32312764, 114.59829868, 131.53755164,
       101.74346117, 105.00215999, 107.22134912,  93.62479231,
        76.9064216 , 106.49390677, 117.42946437,  86.93738026])

Compute the **mean**, **median**, and **mode**

In [35]:
mean = np.mean(numbers)
median = np.median(numbers)
mode = stats.mode(numbers)

print("Mean is ", mean) 
print("Median is ", median)
print("Mode is ", mode)

Mean is  99.52966071621861
Median is  99.64855866366875
Mode is  ModeResult(mode=array([44.47347796]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [46]:
min = np.min(numbers)
max = np.max(numbers)
q1 = np.percentile(numbers, 25)
q3 = np.percentile(numbers, 75)
iqr = stats.iqr(numbers)

print("Minumum number is ", min)
print("Maximum number is ", max)
print("Q1 is" , q1)
print("Q3 is ", q3)
print("IQR is ", iqr)

Minumum number is  44.473477963016016
Maximum number is  147.03192903850493
Q1 is 89.25447233150108
Q3 is  109.83585123787643
IQR is  20.58137890637535

Compute the **variance** and **standard deviation**

In [50]:
variance = np.var(numbers)
variance

224.68656131270004

In [51]:
std_dev = np.std(numbers)
std_dev

14.989548402560366

Compute the **skewness** and **kurtosis**

In [53]:
skewness = stats.skew(numbers)
kurtosis = stats.kurtosis(numbers)
print("Skewness is ", skewness)
print("Kurtosis is ", kurtosis)

Skewness is  -0.03728086653556152
Kurtosis is  -0.016376410765357008

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [55]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [64]:
y = np.random.randint(100, size = 10)
y

array([34, 40, 73, 92, 98, 77,  8, 86, 86,  4])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [65]:
r = np.corrcoef(x,y)
r

array([[ 1.        , -0.08116761],
       [-0.08116761,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [66]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [67]:
r = x.corr(y)
r

0.7586402890911867

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [69]:
rho = x.corr(y, method= "spearman")
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [71]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [72]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [74]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [76]:
tips.corr("pearson")

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000